;;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

(in-package :evergreen-compose)
(defvar *persistence-test* nil)
(defun test-app-services ()
  (let ((*persistence-test* '("draft" :saved nil)))
    (let ((text (encode-app-state '(*persistence-test*))))
      (setf *persistence-test* :changed)
      (restore-app-state text '(*persistence-test*))
      (check "Durable state survives a fresh value" '("draft" :saved nil) *persistence-test*)
      (restore-app-state "#.(error \"must not run\")" '(*persistence-test*))
      (check "Invalid state preserves defaults" '("draft" :saved nil) *persistence-test*)
      (restore-app-state "(:version 99 :values nil)" '(*persistence-test*))
      (check "Unknown schema preserves defaults" '("draft" :saved nil) *persistence-test*)))
  (let ((*service-requests* (make-hash-table)) (*service-sequence* 0) (received nil)
        (*service-submit* (lambda (&rest args) (declare (ignore args)))))
    (http-get "https://example.org" (lambda (body status error) (setf received (list body status error))))
    (dispatch-service-result '(1 200 "hello" nil))
    (check "HTTP completion reaches Lisp callback" '("hello" 200 nil) received)
    (check "Completion removes callback" 0 (hash-table-count *service-requests*))
    (dispatch-service-result '(1 500 nil "stale"))
    (check "Duplicate completion ignored" '("hello" 200 nil) received)))

(defun test-sample-persistence ()
  (dolist (package '(:evergreen-news :evergreen-chat :evergreen-snack :evergreen-reply :evergreen-lagged :evergreen-caster))
    (let* ((variables (symbol-value (find-symbol "*SAVED-VARIABLES*" package)))
           (dark (find-symbol "*DARK*" package))
           (before (symbol-value dark)))
      (set dark (not before))
      (let ((text (encode-app-state variables)))
        (funcall (find-symbol "RESET" package))
        (restore-app-state text variables)
        (check (format nil "~A restores all selected app data" package) text (encode-app-state variables))
        (check (format nil "~A restores preferences" package) (not before) (symbol-value dark))))))

(defun test-live-feeds ()
  (let* ((package (find-package :evergreen-news))
         (entries (find-symbol "*LIVE-POSTS*" package))
         (bookmarks (find-symbol "*BOOKMARKS*" package))
         (receive (find-symbol "RECEIVE-NEWS" package))
         (fixture '((:key "one" :title "Live Lisp" :link "https://example.org/one" :summary "Readable offline." :author "Ada" :date "Today"))))
    (set entries nil)
    (funcall receive fixture 200 nil)
    (let ((id (getf (first (symbol-value entries)) :id)))
      (set bookmarks (list id))
      (funcall receive fixture 200 nil)
      (check "Feed refresh preserves bookmark identity" id (getf (first (symbol-value entries)) :id))
      (funcall receive nil 0 "Offline")
      (check "News failure keeps cache" 1 (length (symbol-value entries)))
      (funcall receive nil 200 nil)
      (check "Feed rollover retains bookmarked articles" id (getf (first (symbol-value entries)) :id))
      (set (find-symbol "*ARTICLE*" package) id)
      (check-true "Live article renders without sample artwork" (sample-has-text "Readable offline." (funcall (find-symbol "VIEW" package))))))
  (let* ((package (find-package :evergreen-caster))
         (entries (find-symbol "*LIVE-EPISODES*" package))
         (receive (find-symbol "RECEIVE-EPISODES" package))
         (fixture '((:key "ep1" :title "A live episode" :link "https://example.org/one" :summary "Show notes" :date "Today" :audio "https://example.org/one.mp3"))))
    (set entries nil)
    (funcall receive "https://example.org/feed" fixture 200 nil)
    (let ((id (getf (first (symbol-value entries)) :id)))
      (funcall (find-symbol "ENQUEUE" package) id)
      (funcall receive "https://example.org/feed" fixture 200 nil)
      (check "Podcast refresh preserves queued episode identity" id (getf (first (symbol-value entries)) :id))
      (funcall receive "https://example.org/feed" nil 0 "Offline")
      (check "Podcast failure retains cached episodes" 1 (length (symbol-value entries)))
      (funcall (find-symbol "PLAY" package) id)
      (check-true "Live playback uses enclosure URL" (let ((tree (funcall (find-symbol "PLAYER" package))))
        (labels ((contains-source (node)
                   (or (equal "https://example.org/one.mp3" (getf (second node) :source))
                       (some #'contains-source (getf (second node) :children))))) (contains-source tree)))))))

(defun test-news-reader ()
  (check "Reader separates author from Planet Lisp title"
         "Ada" (funcall (find-symbol "STORY-AUTHOR" :evergreen-news) '(:title "Ada: A Lisp story" :author "Planet Lisp")))
  (check "Reader preserves colons within article titles"
         "Macros: a guide" (funcall (find-symbol "STORY-TITLE" :evergreen-news) '(:title "Ada: Macros: a guide" :author "Planet Lisp")))
  (check "Reader preserves single line breaks inside paragraphs"
         (list (format nil "First line~%second line") "Next paragraph")
         (funcall (find-symbol "ARTICLE-PARAGRAPHS" :evergreen-news) (format nil "First line~%second line~%~%Next paragraph")))
  (check "Reader shortens RSS dates" "19 Sep 2026"
         (funcall (find-symbol "STORY-DATE" :evergreen-news) "Sat, 19 Sep 2026 17:55:05 GMT"))
)
