;;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

(in-package :evergreen-compose)

(defun test-drawing-pad ()
  (let ((session (make-compose-session)) (received nil))
    (compose-snapshot session
      (ui :drawing-pad :id "paper" :on-stroke (lambda (stroke) (setf received stroke))))
    (compose-dispatch session '(1 "paper" "stroke" "(\"#234b38\" 8 ((10 20) (30 40)))"))
    (check "Completed ink stroke reaches Lisp as data"
           '("#234b38" 8 ((10 20) (30 40))) received)
    (dolist (wire '("#.(error \"never\")" "(\"red\" 0 ((1 2)))" "(\"red\" 8 ((-1 2)))" "(\"red\" 8 nil)"))
      (check-true "Malformed ink is rejected"
        (handler-case (progn (compose-stroke-value wire) nil) (error () t))))))

(defun test-sketchbook ()
  (load (merge-pathnames "../examples/evergreen-sketchbook/app.lisp" *tests-directory*))
  (let* ((pkg (find-package :evergreen-sketchbook))
         (view (symbol-function (find-symbol "VIEW" pkg)))
         (session (make-compose-session)))
    (flet ((value (name) (symbol-value (find-symbol name pkg)))
           (call (name &rest args) (apply (find-symbol name pkg) args)))
      (call "RESET")
      (compose-snapshot session (funcall view))
      (sample-event session view "paper-1" "stroke" "(\"#234b38\" 8 ((10 20) (30 40)))")
      (check "Sketchbook records a completed stroke" 1 (length (call "CURRENT-STROKES")))
      (sample-event session view "undo" "click")
      (check "Undo removes one stroke" nil (call "CURRENT-STROKES"))
      (sample-event session view "redo" "click")
      (check "Redo restores stroke" 1 (length (call "CURRENT-STROKES")))
      (sample-event session view "undo" "click")
      (sample-event session view "paper-1" "stroke" "(\"#d76a43\" 20 ((100 120)))")
      (check "New ink discards redo history" nil (value "*REDO*"))
      (let ((saved (encode-app-state (value "*SAVED-VARIABLES*"))))
        (call "RESET")
        (restore-app-state saved (value "*SAVED-VARIABLES*"))
        (check "Sketch survives a fresh state restore" 1 (length (call "CURRENT-STROKES"))))
      (call "NEW-SKETCH")
      (check "New sketch starts with blank paper" nil (call "CURRENT-STROKES"))
      (call "OPEN-SKETCH" 1)
      (check "Gallery reopens saved drawing" 1 (length (call "CURRENT-STROKES")))
      (compose-snapshot session (funcall view))
      (sample-event session view "rename" "click")
      (sample-event session view "sketch-title" "change" "First study")
      (sample-event session view "save-title" "click")
      (check "Rename updates the saved sketch" "First study" (getf (call "CURRENT-SKETCH") :title))
      (sample-event session view "color-clay" "click")
      (sample-event session view "brush-24" "click")
      (check "Palette selects the next stroke color" "#c65d3b" (value "*PEN-COLOR*"))
      (check "Brush selects the next stroke width" 24 (value "*PEN-WIDTH*"))
      (sample-event session view "clear" "click")
      (check "Clear waits for confirmation" 1 (length (call "CURRENT-STROKES")))
      (sample-event session view "clear-confirm" "confirm")
      (check "Confirmed clear removes ink" nil (call "CURRENT-STROKES")))))
