;;;; SPDX-FileCopyrightText: Copyright (C) 2026 Anthony Green <green@moxielogic.com>
;;;; SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

(in-package :evergreen-caster)

(defparameter *shows*
 '((:id 1 :title "Evergreen Notes" :cover "cover_1.png" :description "Short Common Lisp ideas for your next REPL session.")
   (:id 2 :title "The Lisp Workshop" :cover "cover_2.png" :description "Small tools and clear boundaries for growing programs.")
   (:id 3 :title "Evergreen on Android" :cover "cover_3.png" :description "Native app interfaces, described in Common Lisp.")))

(defparameter *episodes*
 '(
  (:id 1 :show 1 :title "Meet the REPL" :description "A short conversation with your running program." :seconds 34 :audio "episode_1.wav" :transcript "Welcome to Evergreen Notes. This is a synthetic narration of an original Common Lisp sample. The read, evaluate, print loop lets you ask a running Lisp environment small questions. Define a function, call it with a simple input, and inspect the result. Change the function and evaluate its definition again. Later ordinary calls use the new definition. When an experiment reveals useful behavior, save an assertion in your project. The REPL makes a question cheap to ask. A saved check makes its answer repeatable.")
  (:id 2 :show 1 :title "Functions are values" :description "Pass behavior directly with a closure." :seconds 28 :audio "episode_2.wav" :transcript "In Common Lisp, a function is a value. You can pass it as an argument or return it from another function. A closure can keep access to a lexical binding from the place where it was created. In Evergreen Compose, a button callback can close over the identifier of a story. When you tap the button, the callback selects that story. Give state a clear owner, capture the values the callback needs, and keep the view function easy to read.")
  (:id 3 :show 2 :title "Packages and systems" :description "Two boundaries with two different jobs." :seconds 32 :audio "episode_3.wav" :transcript "Welcome to The Lisp Workshop. Packages organize symbol names. Systems describe source files and dependencies. Define package declares a package and its exported symbols. In package tells the reader where to resolve the names in the forms that follow. An ASDF system describes which files belong to your program and how to load them. A package is not a folder. A system is not a namespace. Giving each boundary one job makes a growing application easier to understand.")
  (:id 4 :show 2 :title "Thinking in sequences" :description "Select, transform, and combine your data." :seconds 31 :audio "episode_4.wav" :transcript "A list of reading times is a useful small example. Remove if not keeps the values that satisfy a predicate. Map car transforms each element of a list into a new result. Reduce combines values, such as adding reading times to get a total. Use an initial value when the empty input needs a defined result. Common Lisp also has vectors and strings. The map function accepts sequences and a result type. Choose the operation that fits the collection in front of you.")
  (:id 5 :show 3 :title "Views from state" :description "One bookmark, shown in several places." :seconds 31 :audio "episode_5.wav" :transcript "Welcome to Evergreen on Android. A bookmark belongs to the application. The star on a row is one view of that information. Keep saved story identifiers in one place. Your feed, article screen, and saved list can then read the same state. A callback changes the saved identifiers. The view function describes what to display from the current value. This sample keeps its state in memory. Persistent storage needs a separate loading and saving design.")
  (:id 6 :show 3 :title "A shared native foundation" :description "Lisp application code, native Android controls." :seconds 34 :audio "episode_6.wav" :transcript "Evergreen Compose connects Common Lisp view descriptions to native Android controls. The application supplies data, view functions, and callbacks. The shared runtime handles the controls. Scrolling runs on the Android user interface thread without calling Lisp for every frame. Application callbacks run on the Lisp worker. Start with one screen and one useful interaction. Then add a second screen, test Back, and give repeated list items stable identifiers. Small complete flows make good examples.")))
