;;;; Turn Material's SVG icons into Lisp path data. Run OFFLINE.
;;;;
;;;;   tools/make-icons.sh ~/git/mobile/material-design-icons src/icons-material.lisp \
;;;;       search menu close ...
;;;;
;;;; A phone should not parse SVG at startup and a path is a constant, so the
;;;; conversion happens here and the result is read like any other source.

(load (merge-pathnames "../load.lisp" *load-truename*))
(in-package :bliss)

(defun read-file-string (path)
  (with-open-file (in path :direction :input)
    (let ((text (make-string (file-length in))))
      (subseq text 0 (read-sequence text in)))))

(defun make-icons (manifest output)
  "MANIFEST is lines of NAME<tab>PATH. Writes OUTPUT as a Lisp source file."
  (let ((icons '()) (skipped '()))
    (with-open-file (in manifest :direction :input)
      (loop for line = (read-line in nil)
            while line
            do (let* ((tab (position #\Tab line))
                      (name (subseq line 0 tab))
                      (file (subseq line (1+ tab))))
                 (handler-case
                     (let ((commands (loop for d in (svg-path-strings (read-file-string file))
                                           append (parse-svg-path d))))
                       (if commands
                           (push (cons name commands) icons)
                           (push (list name "no painted path") skipped)))
                   (error (e) (push (list name (princ-to-string e)) skipped))))))
    (with-open-file (out output :direction :output :if-exists :supersede
                                :if-does-not-exist :create)
      (format out ";;;; Generated by tools/make-icons.sh -- do not edit.~%")
      (format out ";;;; Material Design Icons, Apache License 2.0.~%")
      (format out ";;;; https://github.com/google/material-design-icons~%~%")
      (format out "(in-package :bliss)~%~%(defparameter *material-icons*~%  (list~%")
      (dolist (icon (reverse icons))
        ;; arrow_back becomes :ARROW-BACK: the file names are Material's, the
        ;; keywords are ours.
        (format out "   ~S~%   '(" (intern (substitute #\- #\_ (string-upcase (car icon)))
                                           :keyword))
        (dolist (command (cdr icon)) (format out "~%     ~S" command))
        (format out ")~%"))
      (format out "   )~%  \"Material icons as path data in a 24-unit box.\")~%~%")
      ;; PREPENDED, so a real Material icon wins over the computed stopgap of
      ;; the same name -- GETF takes the first match.
      (format out "(setf *icons* (append *material-icons* *icons*))~%"))
    (format t "~D icons written to ~A~%" (length icons) output)
    (when skipped
      (format t "~D skipped:~%" (length skipped))
      (dolist (s (reverse skipped)) (format t "  ~A: ~A~%" (first s) (second s))))))
