#!/bin/sh
# Copy the Bliss sources into a TorCL Android project's assets directory.
#
# APK assets are a flat namespace, so the src/ tree is flattened to bliss-*.lisp
# and a bliss.lisp is generated that LOADs them in dependency order. An app then
# needs one line: (load "bliss.lisp").
set -eu
[ $# -eq 1 ] || { echo "usage: $0 <android-project-dir>" >&2; exit 2; }
here=$(cd "$(dirname "$0")/.." && pwd)
assets="$1/assets"
[ -d "$assets" ] || { echo "no assets directory: $assets" >&2; exit 1; }

# Order matters and matches bliss.asd; backend/gles is last because it is the
# only file that assumes an EGL context exists.
# backend/software ships too. It is not desktop-only scaffolding: it is the
# rasterizer, and on Android it is what an ANativeWindow_lock backend blits from.
# Leaving it out made BLISS:MAKE-SURFACE undefined on the device.
files="package geometry paint font view layout display backend/software jni backend/canvas backend/gles"
: > "$assets/bliss.lisp"
echo ";;;; Generated by tools/sync-assets.sh -- do not edit." >> "$assets/bliss.lisp"
for f in $files; do
  flat="bliss-$(echo "$f" | tr '/' '-').lisp"
  cp "$here/src/$f.lisp" "$assets/$flat"
  echo "(load \"$flat\")" >> "$assets/bliss.lisp"
done
# Refuse to ship unbalanced parens. A reader error on the device shows up as
# "stream error: unterminated list" with no file and no line, after a full
# build-install-launch cycle; here it costs nothing and names the file.
if ! python3 "$here/tools/balance.py" $(for f in $files; do echo "$here/src/$f.lisp"; done) \
        "$assets/app.lisp" | grep -v ': balanced$'; then
  echo "synced $(echo $files | wc -w) files to $assets"
else
  echo "REFUSING to sync: unbalanced parentheses above" >&2
  exit 1
fi
