#!/bin/sh
# Copy the Bliss sources into a TorCL Android project's assets directory.
#
# APK assets are a flat namespace, so the src/ tree is flattened to bliss-*.lisp
# and a bliss.lisp is generated that LOADs them in dependency order. An app then
# needs one line: (load "bliss.lisp").
set -eu
[ $# -eq 1 ] || { echo "usage: $0 <android-project-dir>" >&2; exit 2; }
here=$(cd "$(dirname "$0")/.." && pwd)
assets="$1/assets"
[ -d "$assets" ] || { echo "no assets directory: $assets" >&2; exit 1; }

# Order matters and matches bliss.asd; backend/gles is last because it is the
# only file that assumes an EGL context exists.
files="package geometry paint font view layout display backend/gles"
: > "$assets/bliss.lisp"
echo ";;;; Generated by tools/sync-assets.sh -- do not edit." >> "$assets/bliss.lisp"
for f in $files; do
  flat="bliss-$(echo "$f" | tr '/' '-').lisp"
  cp "$here/src/$f.lisp" "$assets/$flat"
  echo "(load \"$flat\")" >> "$assets/bliss.lisp"
done
echo "synced $(echo $files | wc -w) files to $assets"
